### ISSUE TITLE
Cant run jar on macs

### ISSUE THREAD

**Issue by acamilo** [madhephaestus/bowler-script-kernel#1]
```
localhost:Downloads acamilo$ java -jar BowlerScriptingKernel.jar -s oscar.groovy
Bowler Scripting#

Exception in thread "main" java.lang.RuntimeException: OPENCV_DIR was not found, environment variable OPENCV_DIR needs to be set
    at com.neuronrobotics.imageprovider.OpenCVJNILoader.load(OpenCVJNILoader.java:60)
    at com.neuronrobotics.bowlerstudio.BowlerKernel.main(BowlerKernel.java:30)
localhost:Downloads acamilo$ 
```

**Comment by madhephaestus** [comment]
7d2b936 closes this issue. The readme now includes the instructions you need to run the jar on macs.
